expt_id: 1-1

#  Hyperparameters that uniquely identify the model(s)/training run(s) to analyze
load:  
  expt_id: 1

  disturbance:  # during training
    type: curl
    # list -> load multiple models
    std: [0.0, 0.5, 1.0] #! , 1.5]  
    
  model:  
    n_steps: 100  # TODO: Move this out a level
    hidden_size: 50  #! 100
    feedback_noise_std: 0.01
    motor_noise_std: 0.01
    feedback_delay_steps: 4
    
  train:
    where: 
      0: ['step.net.hidden', 'step.net.readout']
    # n_batches: 10000
    # intervention_scaleup_batches=[0,0],
    # state_reset_iterations=[],
    # readout_norm_loss_weight: 0.0
    # readout_norm_value: 2.0
  
eval_n: 5
  
task:  # Passed to the base task constructor
  full:
    eval_grid_n: 2
    eval_n_directions: 24
    # eval_reach_length: 0.5
  small:
    eval_grid_n: 1
    eval_n_directions: 7
    # eval_reach_length: 0.5

disturbance:
  # null -> same as during training, e.g. load.disturbance.type in this case
  type: null 
  amplitude: [0.0, 0.5, 1.0, 2.0, 4.0] 
  # constant -> [0.0, 0.05, 0.1, 0.2, 0.4],

model:
  n_steps: null
  feedback_noise_std: null
  motor_noise_std: null

analyses:
  center_out_sets: 
    i_replicate: null
    
  
  