expt_id: 1-2

#  Hyperparameters that uniquely identify the model(s)/training run(s) to analyze
load:  
  expt_id: 1

  pert:  # during training
    type: curl
    std: [0.0, 0.5, 1.0, 1.5]  # list -> load multiple models
    
  model:  # 
    n_steps: 100  
    hidden_size: 100
    feedback_noise_std: 0.01
    motor_noise_std: 0.01
    feedback_delay_steps: 0
    
  train:
    where: 
      0: ['step.net.hidden', 'step.net.readout']

eval_n: 5

task:  # Passed to the base task constructor
  full:
    eval_grid_n: 5
    eval_n_directions: 1
    eval_reach_length: 0

pert:
  # null -> same as during training, e.g. load.pert.type in this case
  type: impulse  # not used for anything but reference
  # TODO: Add the calculation of `amplitude` when loading hyperparams
  amplitude_max: 
    fb_pos: 1.8
    fb_vel: 1.2
  n_amplitudes: 3
  start_step: 30
  duration: 5
  direction: rand  # 'rand' or 'xy'

model:
  feedback_noise_std: null
  motor_noise_std: null

  
  
  