id: 2

#  Hyperparameters that uniquely identify the model(s)/training run(s) to analyze
load:  
  id: 1

  disturbance:  # during training
    type: curl
    stds: [0.0, 0.5, 1.0, 1.5]  # list -> load multiple models
    
  model:  # 
    hidden_size: 50
    feedback_noise_std: 0.01
    motor_noise_std: 0.01
    feedback_delay_steps: 0
    where_train_strs: 
      0: ['step.net.hidden', 'step.net.readout']
  
eval: 
  n: 5
  grid_n: 5
  

disturbance:
  # null -> same as during training, e.g. load.disturbance.type in this case
  type: impulse  # not used for anything but 
  amplitude_max: 
    fb_pos: 1.8
    fb_vel: 1.2
  n_amplitudes: 3
  start_step: 30
  duration: 5

model:
  feedback_noise_std: null
  motor_noise_std: null
  
  
  