expt_id: 1-3

#  Hyperparameters that uniquely identify the model(s)/training run(s) to analyze
load:  
  expt_id: 1

  disturbance:  # during training
    type: curl
    std: [0.0, 0.5, 1.0]  # list -> load multiple models
    
  model:  # 
    n_steps: 100
    hidden_size: 100
    feedback_noise_std: 0.01
    motor_noise_std: 0.01
    feedback_delay_steps: 0
  
  train:
    where: 
      0: ['step.net.hidden', 'step.net.readout']

eval_n: 50
  
task:  # Passed to the base task constructor
  full:
    eval_grid_n: 10
    eval_n_directions: 1
    eval_reach_length: 0

disturbance:
  # null -> same as during training, e.g. load.disturbance.type in this case
  type: null 
  amplitude: [0, 0.5, 1.0, 2.0, 4.0] 

model:
  n_steps: 200
  feedback_noise_std: null
  motor_noise_std: null
  
  
  