expt_id: 2-1

#  Hyperparameters that uniquely identify the model(s)/training run(s) to analyze
load:  
  expt_id: 2

  disturbance:  # during training
    type: curl
    # list -> load multiple models
    std: [0.0, 1.0] #! , 0.5, 1.5]  
    
  model:  
    n_steps: 100  # TODO: Move this out a level
    hidden_size: 100
    feedback_noise_std: 0.01
    motor_noise_std: 0.01
    feedback_delay_steps: 0
    
  train:
    where: 
      0: ['step.net.hidden', 'step.net.readout']
    method: 'pai-asf'

context_input: [-1, 0, 1] #! [-2., -1., 0., 1., 2.]

eval_n: 2  #! 5
  
task:  # Passed to the base task constructor
  full:
    eval_grid_n: 2
    eval_n_directions: 7 #! 24
    # eval_reach_length: 0.5
  small:
    eval_grid_n: 1
    eval_n_directions: 7
    # eval_reach_length: 0.5

disturbance:
  # null -> same as during training, e.g. load.disturbance.type in this case
  type: null 
  amplitude: [0.0, 2.0] 
  # constant -> [0.0, 0.4],

model:
  n_steps: null
  feedback_noise_std: null
  motor_noise_std: null

analyses:
  center_out_sets: 
    i_replicate: null
