expt_id: 2-6

#  Hyperparameters that uniquely identify the model(s)/training run(s) to analyze
load:  
  expt_id: 2

  disturbance:  # during training
    type: curl
    # list -> load multiple models
    std: [0.5, 1.0, 1.5]  #! 0  
    
  model:  # 
    n_steps: 100  
    hidden_size: 100
    feedback_noise_std: 0.01
    motor_noise_std: 0.01
    feedback_delay_steps: 0
    
  train:
    where: 
      0: ['step.net.hidden', 'step.net.readout']
    method: 'pai-asf'

eval_n: 2  #! 5

context_input: [-1.0, 0, 1.0]

task:  # Passed to the base task constructor
  full:
    eval_grid_n: 1
    eval_n_directions: 1
    eval_reach_length: 0

disturbance:
  plant:
    directions: 24
    amplitude: 1  
    start_step: 30
    duration: 5
  unit:
    amplitude: 1
    start_step: 30
    duration: 5

model:
  n_steps: null
  feedback_noise_std: null
  motor_noise_std: null

  
  
  