expt_id: 2-6

#  Hyperparameters that uniquely identify the model(s)/training run(s) to analyze
load:  
  expt_id: 2

    
  model:  # 
    n_steps: 100  
    hidden_size: 100
    feedback_noise_std: 0.01
    motor_noise_std: 0.01
    feedback_delay_steps: 0
    
  train:
    method: 'pai-asf'
    where: 
      0: ['step.net.hidden', 'step.net.readout']
    pert: 
      type: curl
      # list -> load multiple models
      std: [0, 1.0] # [0, 0.5, 1.0, 1.5]  

eval_n: 10

context_input: [-2.0, -1.0, 0, 1.0, 2.0]

task:  # Passed to the base task constructor
  full:
    eval_grid_n: 1
    eval_n_directions: 1
    eval_reach_length: 0

pert:
  plant:
    directions: 24
    amp: 1  
    start_step: 30
    duration: 5
  unit:
    amp: 1
    start_step: 30
    duration: 5

model:
  n_steps: null
  feedback_noise_std: 0  #! null
  motor_noise_std: 0  #! null

  
  
  