expt_id: 2-7

#  Hyperparameters that uniquely identify the model(s)/training run(s) to analyze
load:  
  expt_id: 2

  pert:  # during training
    type: curl
    # list -> load multiple models
    std: [0, 0.5, 1.0, 1.5]  
    
  model:  
    n_steps: 100  
    hidden_size: 100
    feedback_noise_std: 0.01
    motor_noise_std: 0.01
    feedback_delay_steps: 0
    
  train:
    where: 
      0: ['step.net.hidden', 'step.net.readout']
    method: 'pai-asf'

eval_n: 10

task:  # Passed to the base task constructor
  full:
    eval_grid_n: 1
    eval_n_directions: 1
    eval_reach_length: 0

pert:
  context:
    step: 30
    c_min: 0
    c_max: 1

model:
  n_steps: null
  feedback_noise_std: null
  motor_noise_std: null

  
  
  