expt_id: 2

disturbance:
  type: curl
  std: [0, 0.5, 1.0, 1.5]  

model:
  n_replicates: 5
  hidden_size: 100
  feedback_delay_steps: 0
  feedback_noise_std: 0.01
  motor_noise_std: 0.01
  dt: 0.05
  n_steps: 100
  damping: 0.05
  control_loss_scale: 1.0

train:  
  method: ['pai-asf']  #! , 'bcs']
  learning_rate_0: 0.01
  n_batches_condition: 10000
  n_batches_baseline: 0
  batch_size: 250
  where: 
    0: ['step.net.hidden', 'step.net.readout']
    # Example: Stop training the readout weights on iteration 1000:
    # 1000: ['step.net.hidden']
  # save_model_parameters: 
  # readout_norm_loss_weight:
  # readout_norm_value:
  n_scaleup_batches: 0
  constant_lr_iterations: 0
  cosine_annealing_alpha: 1.0
  weight_decay: 0.0
  state_reset_iterations: []
    