model:
    n_steps: 100
    hidden_size: 100
    feedback_noise_std: 0.01
    motor_noise_std: 0.01
    mass: 1.0

task:
    eval_grid_n: 1
    eval_n_directions: 7
    eval_reach_length: 0.5
    workspace: ((-1., -1.), (1., 1.))
    
replicate_criterion: "best_total_loss"
    