
# Relative paths are relative to this YAML file
db: /tmp/rnns_learn_robust_motor_policies/db
models: /tmp/rnns_learn_robust_motor_policies/models
figures: /tmp/rnns_learn_robust_motor_policies/figures
figures_dump: /tmp/rnns_learn_robust_motor_policies/figures_dump