
# If `base == ""`, then the remaining keys are interpreted as absolute paths,
# or as relative to this YAML file
base: /tmp/rnns_learn_robust_motor_policies

db: db
models: models
figures: figures
figures_dump: figures_dump
cache: cache