#  Hyperparameters that uniquely identify the model(s)/training run(s) to analyze
train:
  model:  # 
    n_replicates: 5
    n_steps: 100  
    hidden_size: 100
    feedback_noise_std: 0.01
    motor_noise_std: 0.01
    feedback_delay_steps: 0
    damping: 0.05
  method: 'pai-asf'
  where: 
    0: ['step.net.hidden', 'step.net.readout']
  pert: 
    type: curl
    # list -> load multiple models
    std: [0, 1.5] 
    
eval_n: 10

context_input: [-2.0, 0, 2.0]

task:  # Passed to the base task constructor
  full:
    eval_grid_n: 1
    eval_n_directions: 1  #! 
    eval_reach_length: 0.0

pert:
  plant:
    amp: [0.0, 4.0]  
    type: curl
  unit:
    amp: [0.0, 1.0] 
    start_step: 30
    duration: 10

model:
  n_steps: 200
  feedback_noise_std: null
  motor_noise_std: null

  
  
  