expt_id: 2-4

#  Hyperparameters that uniquely identify the model(s)/training run(s) to analyze
train:
  expt_id: 2
  model:   
    n_steps: 100  
    hidden_size: 100
    feedback_noise_std: 0.01
    motor_noise_std: 0.01
    feedback_delay_steps: 0
    dt: 0.05
  # where: 
  #   0: ['step.net.hidden', 'step.net.readout']
  pert:  # during training
    type: curl
    std: [0.0, 1.0]  #! 0.5, 1.5
    # std: [0.0, 0.04]

context_input: [-2., 0., 2.]  #![-3., -2., -1., 0., 1., 2., 3.]

eval_n: 4 #! 25

task:  # Passed to the base task constructor
  full:
    eval_grid_n: 5
    eval_n_directions: 1
    eval_reach_length: 0

model:
  n_steps: null
  feedback_noise_std: null
  motor_noise_std: null
  # damping: 0.0
  
  
  