disturbance:
  stds: 
    curl: [0, 0.5, 1.0, 1.5]
    constant: [0, 0.01, 0.1, 1]

  type: curl

model:
    n_replicates: 5
    hidden_size: 100
    feedback_delay_steps: 4
    feedback_noise_std: 0.01
    motor_noise_std: 0.01
    dt: 0.05
    n_steps: 100
    # intervention_scaleup_batches: intervention_scaleup_batches
    control_loss_scale: 0.1

training:
    learning_rate_0: 0.01
    constant_lr_iterations: 0
    cosine_annealing_alpha: 1.0
    weight_decay: 0.0
    n_batches_condition: 500
    n_batches_baseline: 0
    n_scaleup_batches: 0
    batch_size: 250
    where_train_strs: 
      0: ['step.net.hidden', 'step.net.readout']
      # Example: Stop training the readout weights on iteration 1000
      # 1000: ['step.net.hidden']
    # save_model_parameters: 
    # readout_norm_loss_weight:
    # readout_norm_value:
    state_reset_iterations: []
    